<?php

use Drupal\Core\Form\FormStateInterface;

function bootstrap_filters_form_alter(&$form, FormStateInterface $form_state, $form_id) {


}


/**
 * Implements template_preprocess_views_exposed_form().
 */
function bootstrap_filters_preprocess_views_exposed_form(&$variables) {
  $form = &$variables['form'];

  // Add classes to each exposed filter element
  foreach ($form as $key => &$element) {
    if (!is_array($element) || empty($element['#type'])) {
      continue;
    }

    $element['#attributes']['class'][] = 'col-12';
    $element['#attributes']['class'][] = 'col-md-2';
    $element['#attributes']['class'][] = 'col-lg-3';
  }


}